{"name": "test_login_username_error", "status": "passed", "attachments": [{"name": "stdout", "source": "9ab0d31c-a303-4dc3-b975-5711c234ed6f-attachment.txt", "type": "text/plain"}], "start": 1709085570307, "stop": 1709085570328, "uuid": "22f0abfe-d7cf-49e1-bca7-145734665aa6", "historyId": "1047ca01db95e034c24b7b9b866137fb", "testCaseId": "7d6844bc50864e700b98ea2a6270409d", "fullName": "post1.Testlogin#test_login_username_error", "labels": [{"name": "feature", "value": "用户登录"}, {"name": "story", "value": "用户名错误，登录失败"}, {"name": "suite", "value": "post1"}, {"name": "subSuite", "value": "Testlogin"}, {"name": "host", "value": "WIN-Q4LBVBF2PED"}, {"name": "thread", "value": "8216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "post1"}]}