{"name": "test_login_username_error", "status": "passed", "attachments": [{"name": "stdout", "source": "d809bbcf-0477-406f-bb85-8363373036d6-attachment.txt", "type": "text/plain"}], "start": 1709085516170, "stop": 1709085516192, "uuid": "620010b0-b09f-4bab-be46-da276a97fc6e", "historyId": "1047ca01db95e034c24b7b9b866137fb", "testCaseId": "7d6844bc50864e700b98ea2a6270409d", "fullName": "post1.Testlogin#test_login_username_error", "labels": [{"name": "story", "value": "用户名错误，登录失败"}, {"name": "feature", "value": "用户登录"}, {"name": "suite", "value": "post1"}, {"name": "subSuite", "value": "Testlogin"}, {"name": "host", "value": "WIN-Q4LBVBF2PED"}, {"name": "thread", "value": "936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "post1"}]}